version: 2.1
jobs:

  test:
    working_directory: ~/IaC
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout:
      - run:
        name: Init terraform
        command: terraform init ~/IaC
      - run:
        name: Validate terraform
        command: terraform validate ~/IaC
      - run:
        name: Plan terraform
        command: terraform plan ~/IaC

  deploy:
    working_directory: ~/IaC
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout:
      - run:
        name: Init terraform
      - run:
        name: Apply terraform
        command: terraform apply -auto-approve ~/IaC

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
        requires:
          - hold
        filters:
          branches:
            only: master
