version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  terraform:
    working_directory: ~/project
    docker:
      - image: hashicorp/terraform:light

commands:
  terraform_init:
    steps:
      - run:
          command: apk update; apk add bash curl
      - run:
          name: terraform init
          command: terraform init ~/project

jobs:
  test:
    executor:
      name: terraform
    steps:
      - checkout
      - terraform_init
      - run:
          name: terraform plan
          command: terraform plan ~/project
      - slack/status:
          fail_only: true
          failure_message: ":circleci-fail: テストが失敗しました\n:github_octocat: User:$CIRCLE_USERNAME"
          webhook: "${SLACK_WEBHOOK}"

  deploy:
    executor:
      name: terraform
    steps:
      - checkout
      - terraform_init
      - run:
          name: terraform apply
          command: terraform apply -auto-approve ~/project
      - slack/status:
          channel: "#sns_test"
          success_message: ":ok: デプロイが完了しました\n:github: User:$CIRCLE_USERNAME"
          failure_message: ":ng: デプロイが失敗しました\n:github: User:$CIRCLE_USERNAME"
          webhook: "${SLACK_WEBHOOK}"

workflows:
  test_and_deploy:
    jobs:
      - test:
          context: aws-settings
      - slack/approval-notification:
          message: ":circleci: デプロイを承認してください"
          webhook: "${SLACK_WEBHOOK}"
          requires:
            - test
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
            - slack/approval-notification
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
          context: aws-settings
