version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0

executors:
  terraform:
    working_directory: ~/project
    docker:
      - image: hashicorp/terraform:light

commands:
  terraform_init:
    steps:
      - run:
          name: terraform init
          command: terraform init ~/project

jobs:
  test:
    executor:
      name: terraform
    steps:
      - checkout
      - terraform_init
      - run:
          name: terraform plan
          command: terraform plan ~/project

  deploy:
    executor:
      name: terraform
    steps:
      - checkout
      - terraform_init
      - run:
          name: terraform apply
          command: terraform apply -auto-approve ~/project

workflows:
  test_and_deploy:
    jobs:
      - test:
          context: aws-settings
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
          context: aws-settings
