version: 2
jobs:
  test:
    working_directory: ~/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout:
      - run:
          name: Init terraform
          command: terraform init ~/project
      - run:
          name: Validate terraform
          command: terraform validate ~/project
      - run:
          name: Plan terraform
          command: terraform plan ~/project

  deploy:
    working_directory: ~/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout:
      - run:
          name: Init terraform
          command: terraform init ~/project
      - run:
          name: Apply terraform
          command: terraform apply -auto-approve ~/project

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
